// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/yogerhub/kratos-news-system/app/news/service/internal/biz"
	"github.com/yogerhub/kratos-news-system/app/news/service/internal/conf"
	"github.com/yogerhub/kratos-news-system/app/news/service/internal/data"
	"github.com/yogerhub/kratos-news-system/app/news/service/internal/server"
	"github.com/yogerhub/kratos-news-system/app/news/service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, logger)
	commentRepo := data.NewCommentRepo(dataData, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, logger)
	newsService := service.NewNewsService(articleUsecase, commentUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, newsService, logger)
	registrar := service.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
