#声明版本
version: "3"
services:
  consul:
    #说明采用的镜像地址
    image: cap1573/consul
    volumes:
      - ./consul/data/:/consul/data/
    ports:
      - "8500:8500"

  jaeger:
    image: jaegertracing/all-in-one:1.16
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  #监控
  prometheus:
    image: cap1573/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  #监控看板
  grafana:
    image: cap1573/grafana
    ports:
      - "3000:3000"