global:
  scrape_interval: 15s #默认15秒采集一次
  external_labels:
    monitor: 'go-micro-imooc-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  #监控的服务
  - job_name: 'order'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
      - targets: ['10.211.55.2:8200']